language: node_js
git:
  submodules: false
  depth: 1

addons:
  firefox: latest
  chrome: stable

before_install:
- npm i -g npm@latest

after_success:
- npm run test:codecov

env:
  global:
  - secure: uveWmRaiGKxKAYEP86LTSGmTmUvIXqBi0uNai087MDKvzdPuMQZSay3DSN9MLxAskbch1OjKoRCpkKy+z6tJsQL5z8tptpEcI5mD7LJU8U2akskEXANgqH8nPjqC0YPMPU2y8gWSLd/y22VaIKsF8WxXmVpjc57EXrXQtSqCUI9PI3cnyw9eqcv6Pf+3iXLEL4nr+ORvq+bQgEYk8U6ME+49KULRz+R4VhltZxy5F7T0vFEpAyRfsVYyKBwPss1NXE/M+EMqECRgTyXe1+roDO+DFHP+L0qrOrNEbjJSY5iYDfYOIfdtNYz6rvSbTl9jmsLYphb/BJy4eEB1DV38/K3WJ510gi0n3lWgFPlZB9Wh3S7LXQh4yieHbB2ddWYtX6IP9LNeNpdn/vgJwmuNyiAYsEdeqYdPSUynJ50RlwDVCLd4GkB5qpMBjMgtfXiY4NkqDECjc0BykjKqBZR4iWlDKygFVmBHAgzWrylNAhhiHcClRBLXaRoLa4/lJrpfefVShs5G+y5vxfptDFIbeQs6R2k6Xy5JTx36qMUZoVvdLyg+FqAjaadUGzVNadGw8Sk2DrVODigGB9Zbrmvay8yOYJL2/3JVD2SJua7wEaJnltIItG2F1smR4EcyxDKcOOUhPeat+vm2bXCCYf1MEgw+46iNIxIS05BD+B2aumk=
  - secure: tuCHqcmWvzE5diSBB7jcgAbkzvEbUktR7eCn6wx2A/ntJmmEm2PRuoYQjIX99hF5d16QwgbxunjWihvLYskL7+t+Cwx4K9pyGFUojFQFK7X72py3ZGWrTRL0b1YdtZJ4tZjOK5C4IRy5FmMYV4OP3QHL7aeamFJikCdLHXiT3zfHjlsAwS4pHN8yfmcYgf5+xOrZ9FqVQu6M/HSJIOq/wpEKdFv7dZCxHcsPhjIAO4yCyfUw7pvk0RzOv7owf9LDIGpH5X8wI9GxzuREXSyzX3KBa2a1FdX8ctrxNTAjUepY4AjxAk6ZCcNUHcTeeOfVtZIfztGvryQddhvdWIveMUiGeiLS26L8sEo1xVcVLXpff3LB3vKHIoaDAiGAfp1ZAjRhMAI08yqE61E0h3n+5/fwgcni6p9gdp0eyfRv+QImxUFM+5caI7U6KkP5pjfRWi6zpLu1txCLKXeeh5IiKgnEHBtPu9LeM1UvOIqObOElXuRuPGuJAOH75mtferiWQL2kjjZlZSNGq0/ra+mn6HccuhDq7aIacOkrrz0q0oLSjGCknlCWmgfeP4P3zgm60+vbnOxM6PMm1avDibPyY2zdewGuvVg1p1CmUOoapbttzbptwOfFde/8U/AaSvMTehSTakSnMTj9JBiUa8mQZwRy64euuL2WZaX+D7DGwz4=
  - secure: mIxTbk9QmMvSJ2BJL3rD/TBJppH4JIaMatoBBLsQzJYPtPzhvoEdgsPySh2jf3DAx7IUiQGbQEGsEyLfARanwZIkh5DggHWdMvYsP0ypCiNR7KV7BHCPfQd9v4OW7WF/KQCXzN3TIH+07KvF2swaNuEhKwnI+joVWMMgmEsCWQlTFiEbnieb2xxTMNrzl1WsrtANC9aQTeWVsNcW8xtDA/aQYefaQykOjHPJyyWaiLeBZ9Te0nMD7SeCSQUVywLT77saQJfsnHiCIKvv4lk+rvi6hQypAjBSznFwBa+Zkgk6y5DjT0SDhYXUVY3Kb8AJDFhgIwRlz74/ST9lGuEGnOjHZcQfqarbhcgbg8/HrsPP+spZwa4h0eRPNHfSDmrxTFDZXYDkULeLFPheMkvKKSqq0O+QdMmaL7hPuNWmEQINQg+quxHTjj/ldolL9Vb5db2zMu/jAYGmPDqQOk3GCilUcT4Eh64NmwEShfPY3VMuO/Weg37MJaFNX2efcKxCRWthpwEApqg/4GSk2Qeev7TY/mKkxNFXiXjMwjrXpobEtbQf4Kdy/vpyNE1YtxGiXBsSMMheMeDcVG2ryxaMNcKEyB2uncKqMH3jCU2lDJ/xoJfLmx2+FgxlrTtISl424lshQitWPU9co+FzBnXfyyZILxjsJZSzzZXe3ppWqAg=
