name: filestack-js-stage
on:
  push:
    branches: [ stage, fix/*  ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup repository env
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
        registry-url: "https://registry.npmjs.org"
    - name: Install deps
      run: npm install --ignore-scripts
    - name: Run tests
      run: npm test
    - name: Prepare docs
      run: npm run docs
    - name: Publish package to cdn - stage version
      run: npm run publish:s3:stage
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
